pipeline:
  build:
    image: node:boron
    commands:
      - npm install
    when:
      branch: master
      event: push

  publish:
    image: plugins/docker
    registry: docker.soapbubble.online:5000
    repo: docker.soapbubble.online:5000/captemulation/branes
    tag: latest
    when:
      branch: master
      event: push
